### ISSUE TITLE
Suggestion for `set!`: take multiple symbols

### ISSUE THREAD

**Issue by alecStewart1** [udayvir-singh/hibiscus.nvim#8]
Hello!

I thought I'd make a possible suggestion for `set!` and friends. In Emacs, `setq` takes, as its signature describes:

```
(setq [SYM VAL]...)
```

and as the beginning of its docstring says:

> Set each SYM to the value of its VAL.

So you can have 

```
(setq abbrev-mode t
      abbrev-file-name (concat my-local-dir "abbrev.el")
      save-abbrevs 'silent
      auto-insert-mode t
      auto-insert-query nil)
```

Granted I don't really know if it's best that `set!` is able to evaluate forms, but I think taking multiple "symbols" and values would be convenient.

**Comment by udayvir-singh** [comment]
@alecStewart1 I don't think it is a good idea to implement `setq` for vim because vim contains options that have implicit values, for example `number` & `nonumber`; using `setq` syntax you have to explicitly provide a boolean value for the option which would become more tedious to write.

Here is an example:
```fennel
;; With setq syntax
(set! number true
      relativenumber true
      cursorline true
      backup false
      ...)

;; With current syntax
(set! number)
(set! relativenumber)
(set! cursorline)
(set! nobackup)
```

However, if you still want `setq` like syntax you can do something like:
```fennel
(local options {
  number true
  backup false
})

(each [k v (pairs options)]
  (set! k v))
```
